
          services:
            account: 
               build: 
                 context: .
                 dockerfile: ./account/app.dockerfile
               depends_on:
                - account_db
               environment:
                DATABASE_URL :  postgres://<user>:<pass>@<order-db-host>:<port>/<db>?sslmode=disable
               restart: on-failure
            catalog:
              build:
               context: . 
               dockerfile: ./order/app.dockerfile 
              depends_on:
               - catalog_db 
              environment: 
               DATABASE_URL: http://catalog_db:9200
              restart: on-failure
            order: 
              build: 
               context: .
               dockerfile: ./order/app.dockerfile
              depends_on:
               - order_db

              environment:
                DATABASE_URL : postgres://<user>:<pass>@<order-db-host>:<port>/<db>?sslmode=disable
                ACCOUNT_SERVICE_URL : account:8080
                CATALOG_SERVICE_URL : catalog:8080
              restart: on-failure
            graphql:
             build: 
               context: .
               dockerfile: ./graphql/app.dockerfile
             ports:
               - 8080:8080
             depends_on:
              - account 
              - catalog
             environment:
              ACCOUNT_SERIVCE_URL: account:8080
              CATALOG_SERIVCE_URL: catalog:8080
              ORDER_SERVICE_URL: order:8080
             restart: on-failure
              
            account_db:
              build: 
               context: ./account
               dockerfile: ./db.dockerfile
              environment:
               POSTGRES_USER: 
               POSTGRES_PASSWORD: 
               POSTGRES_DB: 
              restart: unless-stopped
            order_db:
              build: 
               context: ./order
               dockerfile: ./db.dockerfile
              environment:
               POSTGRES_DB: 
               POSTGRES_USER: 
               POSTGRES_PASSWORD: 
              restart: unless-stopped
            catalog_db:
              image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
              environment:
               ES_JAVA_OPTS : -Xms1g -Xmx1g
               discovery.type: single-node



